version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb1
    hostname: mongodb
    command: mongod --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'database'
    ports:
      - 27019:27017
